package com.Joedobo27.WUmod;

import com.wurmonline.mesh.GrassData;
import com.wurmonline.mesh.Tiles;
import com.wurmonline.server.behaviours.ModifiedBy;

import java.util.ArrayList;
import java.util.Arrays;


public class HerbDataJDB {
    String descriptor;
    int ordinal;
    byte tileType;
    GrassData.GrowthStage grassLength;
    short category; // A number from com.wurmonline.server.behaviours.Actions
    int itemType; // templateId from com.wurmonline.server.items.ItemTemplateCreator
    byte material;
    int chanceAt1;
    int chanceAt100;
    int difficultyAt1;
    int difficultyAt100;
    ModifiedBy modifiedBy;
    int chanceModifier;
    public static ArrayList<HerbDataJDB> herbEntries = setEntries();

    public HerbDataJDB(final String aDescriptor, final int aOrdinal, final byte aTileType, final GrassData.GrowthStage aGrassLength,
                         final short aCategory, final int aItemType, final byte aMaterial, final int aChanceAt1, final int aChanceAt100,
                         final int aDifficultyAt1, final int aDifficultyAt100, final ModifiedBy aModifiedBy, final int aChanceModifier) {
        this.descriptor = aDescriptor;
        this.ordinal = aOrdinal;
        this.tileType = aTileType;
        this.grassLength = aGrassLength;
        this.category = aCategory;
        this.itemType = aItemType;
        this.material = aMaterial;
        this.chanceAt1 = aChanceAt1;
        this.chanceAt100 = aChanceAt100;
        this.difficultyAt1 = aDifficultyAt1;
        this.difficultyAt100 = aDifficultyAt100;
        this.modifiedBy = aModifiedBy;
        this.chanceModifier = aChanceModifier;
    }

    private static ArrayList<HerbDataJDB> setEntries() {
        return new ArrayList<>(Arrays.asList(
                new HerbDataJDB("GSHORT_ACORN", 0, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)575, 436, (byte)0, 5, 5, 20, 15, ModifiedBy.NEAR_OAK, 50),
                new HerbDataJDB("GSHORT_BARLEY", 1, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)572, 28, (byte)0, 1, 1, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("GSHORT_BASIL", 2, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)573, 359, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GSHORT_BELLADONNA", 3, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)573, 361, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GSHORT_GALIC", 4, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)575, 356, (byte)0, 1, 21, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GSHORT_LOVAGE", 5, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)573, 353, (byte)0, 6, 6, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("GSHORT_NETTLES", 6, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)575, 365, (byte)0, 5, 5, -5, -5, ModifiedBy.WOUNDED, 5),
                new HerbDataJDB("GSHORT_OAT", 7, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GSHORT_OREGANO", 8, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GSHORT_PARSLEY", 9, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 5),
                new HerbDataJDB("GSHORT_ROSMARY", 10, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)573, 363, (byte)0, 5, 5, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("GSHORT_RYE", 11, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GSHORT_SAGE", 12, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 15),
                new HerbDataJDB("GSHORT_SASSAFRAS", 13, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("GSHORT_THYME", 14, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GSHORT_WHEAT", 15, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.WOUNDED, 5),
                new HerbDataJDB("GSHORT_WOAD", 16, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.SHORT, (short)575, 440, (byte)0, 1, 6, 20, 15, ModifiedBy.NO_TREES, 10),
                new HerbDataJDB("GMED_ACORN", 17, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)575, 436, (byte)0, 10, 10, 20, 10, ModifiedBy.NEAR_OAK, 50),
                new HerbDataJDB("GMED_BARLEY", 18, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)572, 28, (byte)0, 1, 1, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("GMED_BASIL", 19, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)573, 359, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GMED_BELLADONNA", 20, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)573, 361, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GMED_GALIC", 21, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)575, 356, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GMED_LOVAGE", 22, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)573, 353, (byte)0, 6, 6, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("GMED_NETTLES", 23, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)575, 365, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("GMED_OAT", 24, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GMED_OREGANO", 25, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GMED_PARSLEY", 26, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 8),
                new HerbDataJDB("GMED_ROSMARY", 27, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)573, 363, (byte)0, 5, 5, -5, -5, ModifiedBy.WOUNDED, 15),
                new HerbDataJDB("GMED_RYE", 28, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GMED_SAGE", 29, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("GMED_SASSAFRAS", 30, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("GMED_THYME", 31, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GMED_WHEAT", 32, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.WOUNDED, 8),
                new HerbDataJDB("GMED_WOAD", 33, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.MEDIUM, (short)575, 440, (byte)0, 1, 10, 20, 10, ModifiedBy.NO_TREES, 20),
                new HerbDataJDB("GTALL_ACORN", 34, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)575, 436, (byte)0, 15, 15, 20, 5, ModifiedBy.NEAR_OAK, 50),
                new HerbDataJDB("GTALL_BARLEY", 35, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)572, 28, (byte)0, 1, 1, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("GTALL_BASIL", 36, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)573, 359, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GTALL_BELLADONNA", 37, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)573, 361, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GTALL_GALIC", 38, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)575, 356, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GTALL_LOVAGE", 39, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)573, 353, (byte)0, 6, 6, -5, -5, ModifiedBy.WOUNDED, 15),
                new HerbDataJDB("GTALL_NETTLES", 40, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)575, 365, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("GTALL_OAT", 41, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GTALL_OREGANO", 42, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GTALL_PARSLEY", 43, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("GTALL_ROSMARY", 44, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)573, 363, (byte)0, 5, 5, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("GTALL_RYE", 45, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GTALL_SAGE", 46, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 12),
                new HerbDataJDB("GTALL_SASSAFRAS", 47, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 12),
                new HerbDataJDB("GTALL_THYME", 48, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GTALL_WHEAT", 49, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("GTALL_WOAD", 50, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.TALL, (short)575, 440, (byte)0, 1, 20, 20, 5, ModifiedBy.NO_TREES, 30),
                new HerbDataJDB("GWILD_ACORN", 51, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)575, 436, (byte)0, 20, 20, 20, 1, ModifiedBy.NEAR_OAK, 50),
                new HerbDataJDB("GWILD_BARLEY", 52, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)572, 28, (byte)0, 1, 1, -5, -5, ModifiedBy.WOUNDED, 5),
                new HerbDataJDB("GWILD_BASIL", 53, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)573, 359, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GWILD_BELLADONNA", 54, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)573, 361, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GWILD_GALIC", 55, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)575, 356, (byte)0, 15, 15, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GWILD_LOVAGE", 56, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)573, 353, (byte)0, 6, 6, -5, -5, ModifiedBy.WOUNDED, 15),
                new HerbDataJDB("GWILD_NETTLES", 57, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)575, 365, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("GWILD_OAT", 58, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GWILD_OREGANO", 59, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GWILD_PARSLEY", 60, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 7),
                new HerbDataJDB("GWILD_ROSMARY", 61, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)573, 363, (byte)0, 5, 5, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("GWILD_RYE", 62, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GWILD_SAGE", 63, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 15),
                new HerbDataJDB("GWILD_SASSAFRAS", 64, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 9),
                new HerbDataJDB("GWILD_THYME", 65, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("GWILD_WHEAT", 66, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.WOUNDED, 6),
                new HerbDataJDB("GWILD_WOAD", 67, Tiles.Tile.TILE_GRASS.id, GrassData.GrowthStage.WILD, (short)575, 440, (byte)0, 1, 40, 20, 1, ModifiedBy.NO_TREES, 40),
                new HerbDataJDB("STEPPE_ACORN", 68, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)575, 436, (byte)0, 5, 5, 20, 10, ModifiedBy.NEAR_OAK, 50),
                new HerbDataJDB("STEPPE_BARLEY", 69, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)572, 28, (byte)0, 1, 7, -5, -5, ModifiedBy.WOUNDED, 7),
                new HerbDataJDB("STEPPE_BASIL", 70, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)573, 359, (byte)0, 8, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("STEPPE_BELLADONNA", 71, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)573, 361, (byte)0, 15, 15, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("STEPPE_GALIC", 72, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)575, 356, (byte)0, 8, 8, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("STEPPE_LOVAGE", 73, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)573, 353, (byte)0, 8, 12, -5, -5, ModifiedBy.WOUNDED, 5),
                new HerbDataJDB("STEPPE_NETTLES", 74, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)575, 365, (byte)0, 2, 2, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("STEPPE_OAT", 75, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("STEPPE_OREGANO", 76, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("STEPPE_PARSLEY", 77, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("STEPPE_ROSMARY", 78, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)573, 363, (byte)0, 15, 5, -5, -5, ModifiedBy.WOUNDED, 5),
                new HerbDataJDB("STEPPE_RYE", 79, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("STEPPE_SAGE", 80, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 5),
                new HerbDataJDB("STEPPE_SASSAFRAS", 81, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 8),
                new HerbDataJDB("STEPPE_THYME", 82, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("STEPPE_WHEAT", 83, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.WOUNDED, 9),
                new HerbDataJDB("STEPPE_WOAD", 84, Tiles.Tile.TILE_STEPPE.id, GrassData.GrowthStage.SHORT, (short)575, 440, (byte)0, 10, 46, 20, 1, ModifiedBy.NO_TREES, 50),
                new HerbDataJDB("MARSH_ACORN", 85, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)575, 436, (byte)0, 5, 5, 10, 10, ModifiedBy.NEAR_OAK, 50),
                new HerbDataJDB("MARSH_BARLEY", 86, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)572, 28, (byte)0, 1, 1, -5, -5, ModifiedBy.WOUNDED, 3),
                new HerbDataJDB("MARSH_BASIL", 87, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)573, 359, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MARSH_BELLADONNA", 88, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)573, 361, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MARSH_GALIC", 89, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)575, 356, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MARSH_LOVAGE", 90, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)573, 353, (byte)0, 6, 6, -5, -5, ModifiedBy.WOUNDED, 4),
                new HerbDataJDB("MARSH_NETTLES", 91, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)575, 365, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MARSH_OAT", 92, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MARSH_OREGANO", 93, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MARSH_PARSLEY", 94, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 8),
                new HerbDataJDB("MARSH_ROSMARY", 95, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)573, 363, (byte)0, 15, 15, -5, -5, ModifiedBy.WOUNDED, 17),
                new HerbDataJDB("MARSH_RYE", 96, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MARSH_SAGE", 97, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("MARSH_SASSAFRAS", 98, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MARSH_THYME", 99, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MARSH_WHEAT", 100, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.WOUNDED, 5),
                new HerbDataJDB("MARSH_WOAD", 101, Tiles.Tile.TILE_MARSH.id, GrassData.GrowthStage.SHORT, (short)575, 440, (byte)0, 6, 26, 20, 20, ModifiedBy.NO_TREES, 20),
                new HerbDataJDB("MOSS_ACORN", 102, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)575, 436, (byte)0, 5, 5, 20, 20, ModifiedBy.NEAR_OAK, 50),
                new HerbDataJDB("MOSS_BARLEY", 103, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)572, 28, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MOSS_BASIL", 104, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)573, 359, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MOSS_BELLADONNA", 105, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)573, 361, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MOSS_GALIC", 106, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)575, 356, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MOSS_LOVAGE", 107, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)573, 353, (byte)0, 16, 16, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("MOSS_NETTLES", 108, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)575, 365, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MOSS_OAT", 109, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MOSS_OREGANO", 110, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MOSS_PARSLEY", 111, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MOSS_ROSMARY", 112, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)573, 363, (byte)0, 9, 9, -5, -5, ModifiedBy.WOUNDED, 5),
                new HerbDataJDB("MOSS_RYE", 113, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MOSS_SAGE", 114, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MOSS_SASSAFRAS", 115, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MOSS_THYME", 116, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MOSS_WHEAT", 117, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("MOSS_WOAD", 118, Tiles.Tile.TILE_MOSS.id, GrassData.GrowthStage.SHORT, (short)575, 440, (byte)0, 6, 26, 20, 20, ModifiedBy.NO_TREES, 32),
                new HerbDataJDB("PEAT_ACORN", 119, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)575, 436, (byte)0, 5, 15, 20, 20, ModifiedBy.NEAR_OAK, 40),
                new HerbDataJDB("PEAT_BARLEY", 120, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)572, 28, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("PEAT_BASIL", 121, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)573, 359, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("PEAT_BELLADONNA", 122, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)573, 361, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("PEAT_GALIC", 123, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)575, 356, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("PEAT_LOVAGE", 124, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)573, 353, (byte)0, 16, 16, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("PEAT_NETTLES", 125, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)575, 365, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("PEAT_OAT", 126, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("PEAT_OREGANO", 127, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("PEAT_PARSLEY", 128, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("PEAT_ROSMARY", 129, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)573, 363, (byte)0, 15, 15, -5, -5, ModifiedBy.WOUNDED, 10),
                new HerbDataJDB("PEAT_RYE", 130, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("PEAT_SAGE", 131, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("PEAT_SASSAFRAS", 132, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("PEAT_THYME", 133, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("PEAT_WHEAT", 134, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("PEAT_WOAD", 135, Tiles.Tile.TILE_PEAT.id, GrassData.GrowthStage.SHORT, (short)575, 440, (byte)0, 6, 6, 20, 20, ModifiedBy.NO_TREES, 40),
                new HerbDataJDB("TSHORT_ACORN", 136, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)575, 436, (byte)0, 5, 5, 20, 10, ModifiedBy.NEAR_OAK, 50),
                new HerbDataJDB("TSHORT_BARLEY", 137, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)572, 28, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TSHORT_BASIL", 138, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)573, 359, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TSHORT_BELLADONNA", 139, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)573, 361, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TSHORT_GALIC", 140, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)575, 356, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TSHORT_LOVAGE", 141, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)573, 353, (byte)0, 6, 6, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TSHORT_NETTLES", 142, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)575, 365, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("TSHORT_OAT", 143, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TSHORT_OREGANO", 144, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TSHORT_PARSLEY", 145, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TSHORT_ROSMARY", 146, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)573, 363, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TSHORT_RYE", 147, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TSHORT_SAGE", 148, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("TSHORT_SASSAFRAS", 149, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TSHORT_THYME", 150, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TSHORT_WHEAT", 151, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TSHORT_WOAD", 152, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.SHORT, (short)575, 440, (byte)0, 6, 16, 30, 20, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_ACORN", 153, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)575, 436, (byte)0, 5, 10, 20, 5, ModifiedBy.NEAR_OAK, 50),
                new HerbDataJDB("TMED_BARLEY", 154, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)572, 28, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_BASIL", 155, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)573, 359, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_BELLADONNA", 156, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)573, 361, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_GALIC", 157, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)575, 356, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_LOVAGE", 158, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)573, 353, (byte)0, 6, 6, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_NETTLES", 159, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)575, 365, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("TMED_OAT", 160, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_OREGANO", 161, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_PARSLEY", 162, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_ROSMARY", 163, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)573, 363, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_RYE", 164, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_SAGE", 165, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("TMED_SASSAFRAS", 166, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_THYME", 167, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_WHEAT", 168, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TMED_WOAD", 169, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.MEDIUM, (short)575, 440, (byte)0, 6, 16, 30, 10, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_ACORN", 170, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)575, 436, (byte)0, 5, 15, 20, 1, ModifiedBy.NEAR_OAK, 50),
                new HerbDataJDB("TTALL_BARLEY", 171, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)572, 28, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_BASIL", 172, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)573, 359, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_BELLADONNA", 173, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)573, 361, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_GALIC", 174, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)575, 356, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_LOVAGE", 175, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)573, 353, (byte)0, 6, 6, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_NETTLES", 176, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)575, 365, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("TTALL_OAT", 177, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_OREGANO", 178, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_PARSLEY", 179, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_ROSMARY", 180, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)573, 363, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_RYE", 181, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_SAGE", 182, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("TTALL_SASSAFRAS", 183, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_THYME", 184, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_WHEAT", 185, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("TTALL_WOAD", 186, Tiles.Tile.TILE_TREE.id, GrassData.GrowthStage.TALL, (short)575, 440, (byte)0, 6, 16, 30, 1, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_ACORN", 187, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)575, 436, (byte)0, 5, 5, 20, 15, ModifiedBy.NEAR_OAK, 50),
                new HerbDataJDB("BSHORT_BARLEY", 188, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)572, 28, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_BASIL", 189, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)573, 359, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_BELLADONNA", 190, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)573, 361, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_GALIC", 191, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)575, 356, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_LOVAGE", 192, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)573, 353, (byte)0, 6, 6, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_NETTLES", 193, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)575, 365, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("BSHORT_OAT", 194, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_OREGANO", 195, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_PARSLEY", 196, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_ROSMARY", 197, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)573, 363, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_RYE", 198, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_SAGE", 199, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("BSHORT_SASSAFRAS", 200, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_THYME", 201, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_WHEAT", 202, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BSHORT_WOAD", 203, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.SHORT, (short)575, 440, (byte)0, 6, 16, 20, 10, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_ACORN", 204, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)575, 436, (byte)0, 5, 10, 20, 10, ModifiedBy.NEAR_OAK, 50),
                new HerbDataJDB("BMED_BARLEY", 205, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)572, 28, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_BASIL", 206, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)573, 359, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_BELLADONNA", 207, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)573, 361, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_GALIC", 208, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)575, 356, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_LOVAGE", 209, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)573, 353, (byte)0, 6, 6, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_NETTLES", 210, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)575, 365, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("BMED_OAT", 211, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_OREGANO", 212, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_PARSLEY", 213, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_ROSMARY", 214, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)573, 363, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_RYE", 215, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_SAGE", 216, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("BMED_SASSAFRAS", 217, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_THYME", 218, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_WHEAT", 219, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BMED_WOAD", 220, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.MEDIUM, (short)575, 440, (byte)0, 6, 16, 20, 5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_ACORN", 221, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)575, 436, (byte)0, 5, 15, 20, 1, ModifiedBy.NEAR_OAK, 50),
                new HerbDataJDB("BTALL_BARLEY", 222, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)572, 28, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_BASIL", 223, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)573, 359, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_BELLADONNA", 224, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)573, 361, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_GALIC", 225, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)575, 356, (byte)0, 8, 8, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_LOVAGE", 226, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)573, 353, (byte)0, 6, 6, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_NETTLES", 227, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)575, 365, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("BTALL_OAT", 228, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)572, 31, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_OREGANO", 229, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)573, 357, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_PARSLEY", 230, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)573, 358, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_ROSMARY", 231, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)573, 363, (byte)0, 5, 5, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_RYE", 232, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)572, 30, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_SAGE", 233, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)573, 354, (byte)0, 10, 10, -5, -5, ModifiedBy.WOUNDED, 20),
                new HerbDataJDB("BTALL_SASSAFRAS", 234, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)573, 366, (byte)0, 10, 10, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_THYME", 235, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)573, 360, (byte)0, 7, 7, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_WHEAT", 236, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)572, 29, (byte)0, 1, 1, -5, -5, ModifiedBy.NOTHING, 0),
                new HerbDataJDB("BTALL_WOAD", 237, Tiles.Tile.TILE_BUSH.id, GrassData.GrowthStage.TALL, (short)575, 440, (byte)0, 6, 16, 20, 1, ModifiedBy.NOTHING, 0)
        ));
    }
}
